# Generated by Django 2.1 on 2018-10-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_auto_20181013_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
